# faster_rcnn_R_50_FPN_3x from d2
_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./faster_rcnn_coco.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  STEPS: (210000, 250000)
  MAX_ITER: 2500